RDKCOM-311: CcspTr069PaSsp: link with openssl libcrypto.so
source/Ssp/ccsp_tr069_pa_custom_apis.c is platform specific, but at
least some versions of it make calls to openssl APIs.
Fix for build issues seen with OE 2.3.
 | /usr/src/debug/ccsp-tr069-pa/2.1+gitAUTOINC+208b502a32-r0/git/source/Ssp/ccsp_tr069_pa_custom_apis.c:541: error: undefined reference to 'HMAC_CTX_in
 | /usr/src/debug/ccsp-tr069-pa/2.1+gitAUTOINC+208b502a32-r0/git/source/Ssp/ccsp_tr069_pa_custom_apis.c:542: error: undefined reference to 'EVP_sha256'
 | /usr/src/debug/ccsp-tr069-pa/2.1+gitAUTOINC+208b502a32-r0/git/source/Ssp/ccsp_tr069_pa_custom_apis.c:542: error: undefined reference to 'HMAC_Init'
 | /usr/src/debug/ccsp-tr069-pa/2.1+gitAUTOINC+208b502a32-r0/git/source/Ssp/ccsp_tr069_pa_custom_apis.c:543: error: undefined reference to 'HMAC_Update
 | /usr/src/debug/ccsp-tr069-pa/2.1+gitAUTOINC+208b502a32-r0/git/source/Ssp/ccsp_tr069_pa_custom_apis.c:544: error: undefined reference to 'HMAC_Final'
 | /usr/src/debug/ccsp-tr069-pa/2.1+gitAUTOINC+208b502a32-r0/git/source/Ssp/ccsp_tr069_pa_custom_apis.c:557: error: undefined reference to 'HMAC_CTX_cl
 | collect2: error: ld returned 1 exit status
 | make[3]: *** [CcspTr069PaSsp] Error 1
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

Reason for change: There is abandoned cherry-pick available. CcspTr069PaSsp: link with openssl libcrypto.so
Test Procedure: None.
Risks: Low.

(cherry picked from commit 99e47b711ce9327974988dc0b516b57b597e1722)

(cherry picked from commit 41e159393c8f9874ca1c6dada23b23a5ad8eba17)

Change-Id: I5d88262d0d98013b912a096f6748484c42ce642d